generics/urls.py
from django.urls import path, include
from generics import views

app_name = 'generics'

urlpatterns = [
    path('home/', views.index, name='index'),
]

result/urls.py
from django.urls import path    
from result.views import result, payment

app_name = 'result'

urlpatterns = [
    path('results/', result, name='results'),
    path('buy-card/', payment, name='buy-card')
]

resultPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('college.urls')),
    path('student/', include('student.urls')),
    path('result/', include('result.urls')),
    path('generics/', include('generics.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from student.views import StudentRegistrationView, login_view, logout_view, dasboard_view, StudentProfileView, StudentUpdateView, delete_student

app_name = 'student'

urlpatterns = [
    path('registration/', StudentRegistrationView.as_view(), name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dasboard_view, name='dashboard'),
    path('profile/<int:user_id>/', StudentProfileView.as_view(), name='profile'),
    path('profile/update/<int:user_id>/', StudentUpdateView.as_view(), name='update'),
    path('profile/delete/<int:user_id>', delete_student, name='delete'),
]

college/generics/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    bio = models.TextField(blank=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255)


class collegeUser(CustomUser):
    # Add your additional fields here
    POBox_PMB = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    date_founded = models.DateField(null=True, blank=True)
    

college/student/models.py
from django.db import models
from college.models import Department
from generics.models import CustomUser
from django.core.validators import FileExtensionValidator

class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='college_student')
    password = models.CharField(max_length=120, blank=False, null=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    student_id = models.IntegerField(unique=True)
    matric_number = models.CharField(max_length=50, unique=True)
    profile_picture = models.ImageField(upload_to='profile_picture/Students', default='default_user_icon.png', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])

generics/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db import models

class CustomUser(AbstractUser):
    bio = models.TextField(blank=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=11, blank=True)
    address = models.CharField(max_length=255)

class collegeUser(CustomUser):
    # Add your additional fields her
    POBox_PMB = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    date_founded = models.DateField(null=True, blank=True)
    

student/models.py
from django.db import models
from college.models import Department
from generics.models import CustomUser
from django.core.validators import FileExtensionValidator

STATE_CHOICES = (
    ('Abia Umuahia', 'Abia Umuahia'),
    ('Adamawa Yola', 'Adamawa Yola'),
    ('Akwa Ibom Uyo', 'Akwa Ibom Uyo'),
    ('Anambra Awka', 'Anambra Awka'),
    ('Bauchi Bauchi', 'Bauchi Bauchi'),
    ('Bayelsa Yenagoa', 'Bayelsa Yenagoa'),
    ('Benue Makurdi', 'Benue Makurdi'),
    ('Borno Maiduguri', 'Borno Maiduguri'),
    ('Cross River Calabar', 'Cross River Calabar'),
    ('Delta Asaba', 'Delta Asaba'),
    ('Ebonyi Abakaliki', 'Ebonyi Abakaliki'),
    ('Edo Benin City', 'Edo Benin City'),
    ('Ekiti Ado-Ekiti', 'Ekiti Ado-Ekiti'),
    ('Enugu Enugu', 'Enugu Enugu'),
    ('Gombe Gombe', 'Gombe Gombe'),
    ('Imo Owerri', 'Imo Owerri'),
    ('Jigawa Dutse', 'Jigawa Dutse'),
    ('Kaduna Kaduna', 'Kaduna Kaduna'),
    ('Kano Kano', 'Kano Kano'),
    ('Katsina Katsina', 'Katsina Katsina'),
    ('Kebbi Birnin Kebbi', 'Kebbi Birnin Kebbi'),
    ('Kogi Lokoja', 'Kogi Lokoja'),
    ('Kwara Ilorin', 'Kwara Ilorin'),
    ('Lagos Ikeja', 'Lagos Ikeja'),
    ('Nasarawa Lafia', 'Nasarawa Lafia'),
    ('Niger Minna', 'Niger Minna'),
    ('Ogun Abeokuta', 'Ogun Abeokuta'),
    ('Ondo Akure', 'Ondo Akure'),
    ('Osun Osogbo', 'Osun Osogbo'),
    ('Oyo Ibadan', 'Oyo Ibadan'),
    ('Plateau Jos', 'Plateau Jos'),
    ('Rivers Port Harcourt', 'Rivers Port Harcourt'),
    ('Sokoto Sokoto', 'Sokoto Sokoto'),
    ('Taraba Jalingo', 'Taraba Jalingo'),
    ('Yobe Damaturu', 'Yobe Damaturu'),
    ('Zamfara Gusau', 'Zamfara Gusau'),
    ('Federal Capital Territory Abuja', 'Federal Capital Territory Abuja')
)

class Student(models.Model):
    #id = models.AutoField(primary_key=True)
    #department = models.ForeignKey(Department, on_delete=models.CASCADE
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, default=None)
    first_name = models.CharField(max_length=250, unique=False, null=True)
    last_name = models.CharField(max_length=250, unique=False, null=True)
    state = models.CharField(choices=STATE_CHOICES, max_length=300, default='Delta Asaba')
    city = models.CharField(max_length=200, null=True)
    zipcode = models.IntegerField(null=True)
    matric_number = models.CharField(max_length=50, unique=True, blank=True, null=True)
    #phone = models.IntegerField(default=0, unique=True)
    profile_picture = models.ImageField(upload_to='profile_picture/students', default='default_user_icon.png', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])

college/student/forms.py
from django import forms
from .models import Student

class StudentRegistrationForm(forms.ModelForm):
    '''form for student registration'''
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    class Meta:
        model = Student
        fields = ['user', 'department', 'matric_number', 'profile_picture', 'first_name', 'last_name', 'password']

generics/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from college.models import Colleges


class collegeSignUpForm(UserCreationForm):
    """"""
    class Meta:
        model = Colleges
        fields = ('college_name', 'username', 'email', 'password1', 'password2',)

        

student/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from generics.models import CustomUser
from student.models import Student

class StudentRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        #fields = '__all__'
        fields = ('username', 'email',)
        placeholders = {
            'username': 'Username'
            #'phone_number': 'Phone Number',
            #'birth_date': 'Birth Date',
        }

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-md'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-md'})
            #'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            #'birth_date': forms.DateInput(attrs={'class': 'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'] = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
        self.fields['password2'] = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit==True:
            user.save()

            Student.objects.create(user=user)
            return user


class StudentChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ('username', 'phone_number', 'birth_date')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control'}),
        }


class StudentLoginForm(forms.Form):

    username = forms.CharField(label='username', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = Student
        fields=['first_name', 'last_name', 'matric_number', 'city', 'state', 'zipcode', 'profile_picture']
        # bootstrap classes
        widgets={
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'matric_number':forms.TextInput(attrs={'class':'form-control'}),
        'city':forms.TextInput(attrs={'class':'form-control'}),
        #'phone':forms.NumberInput(attrs={'class':'form-control'}),
        'state':forms.Select(attrs={'class':'form-control'}),
        'zipcode':forms.TextInput(attrs={'class':'form-control'}),
        }

college/generics/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'generics/index.html')

college/student/views.py
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import StudentRegistrationForm

class StudentRegistrationView(FormView):
    template_name = 'generics/student/register2.html'
    form_class = StudentRegistrationForm
    success_url = reverse_lazy('')

    def form_valid(self, form):
        '''checks if form is valid'''
        password = form.cleaned_data.get('password')
        confirmpassword = form.cleaned_data.get('confirmpassword')

        if confirm_password != password:
            form.add_error('confirm_password, password do not  match')
            return self.form_invalid(form)

        form.save()
        return super().form_valid(form)

generics/views.py
from django.shortcuts import render
from .forms import collegeSignUpForm

# Create your views here.

def index(request):
    return render(request, 'generics/index.html')

def login(request):
    return render(request, 'generics/login.html')

def signup(request):
    form = collegeSignUpForm()
    return render(request, 'generics/signup.html', {'form': form})

student/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from student.forms import StudentRegistrationForm, StudentLoginForm, StudentProfileForm
from django.views.generic.edit import CreateView
from generics.models import CustomUser
from django.urls import reverse_lazy, reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from student.models import Student
from student.serialized import ImageResizeMixin
from django.http import HttpResponseForbidden

class StudentRegistrationView(CreateView):
    template_name = 'generics/student/register.html'
    form_class = StudentRegistrationForm
    success_url = reverse_lazy('student:login')

'''def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # Authenticate user
            user = form.get_user()
            # Login the user
            login(request, user)
            # Redirect to a success page
            return redirect('result:results')
    else:
        form = AuthenticationForm()
    return render(request, 'generics/student/login.html', {'form': form})
'''

def login_view(request):
    if request.method == 'POST':
        form = StudentLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('student:dashboard')
            else:
                error_message = 'username or password does not exist'
                return render(request, 'generics/student/login.html', {'form': form})
    else:
        form = StudentLoginForm()
    return render(request, 'generics/student/login.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('student:login')

@login_required
def dasboard_view(request):
    student = get_object_or_404(Student)
    return render(request, 'generics/student/dashboard.html' , {student: 'student'})

class StudentProfileView(View):
    '''student profile'''
    def get(self, request, user_id):
        student = get_object_or_404(Student, user_id=user_id)
        context = {'student':student}
        return render(request, 'generics/student/student_profile.html', context)

class StudentUpdateView(ImageResizeMixin, View):
    '''update student profile'''

    def get(self, request, user_id):
        student = get_object_or_404(Student, user_id=user_id)
        form = StudentProfileForm(instance=student)
        context = {
                'form':form,
                }
        return render(request, 'generics/student/student_update.html', context)

    def post(self, request, user_id):

        #imgPath = '../media/profile_picture/students'
        #avePath = '../media/profile_picture/students/resized'
        ##self.resizeImage(imgPath, savePath, width=200, height=200)

        student = Student.objects.get(user_id=user_id)
        form = StudentProfileForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulations! Profile updated successfully.')
            return redirect('student:profile', user_id=user_id)
        else:
            messages.warning(request, 'Invalid input data.')
            return redirect('student:update', user_id=user_id)

def delete_student(request, user_id):
    '''delete a student'''
    student = get_object_or_404(Student, user_id=user_id)
    student.delete()
    return redirect('student:registration')

generics/templates/generics/student/dashboard.html
{% extends 'generics/student/index.html' %}
{% block title %}
student dashboard
{% endblock title %}

{% block content %}
<form>
  <!-- <div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Card.no</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3">
    </div>
  </div>-->
  <p> Hi, {{ user.username }} </p>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Mat.no</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3">
    </div>
  </div>
  <div class="col-auto mb-3">
    <label class="visually-hidden" for="autoSizingSelect">Preference</label>
    <select class="form-select" id="autoSizingSelect">
      <option selected>Session</option>
      <option value="1">One</option>
      <option value="2">Two</option>
      <option value="3">Three</option>
    </select>
  </div>
  <div class="col-auto mb-3">
    <label class="visually-hidden" for="autoSizingSelect">Preference</label>
    <select class="form-select" id="autoSizingSelect">
      <option selected>Semester</option>
      <option value="1">One</option>
      <option value="2">Two</option>
      <option value="3">Three</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Check Result</button>

</form>
{% endblock content %}

generics/templates/generics/student/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Dashboard - Student {% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/pay.css' %}">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        {% block extra_head %}{% endblock %}
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
	    <a class="navbar-brand ps-3" href="#">Students Dashboard</a>
            <!-- Sidebar Toggle-->
	    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
			    <li><a class="dropdown-item" href="{% url 'student:profile' user.id %}">Profile</a></li>
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
			<li><a class="dropdown-item" href="{% url 'result:results' %}">Results</a></li>
                        <li><hr class="dropdown-divider" /></li>
			{% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'student:logout' %}">Logout</a></li>
			{% else %}
			<li><a class="dropdown-item" href="{% url 'student:login' %}">Login</a></li>
			{% endif %}
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		    <div class="offcanvas-header">
			    <h1 class="offcanvas-title" id="offcanvasExampleLabel">{{ user.username }}</h1>
			<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		    </div>
		    <div class="offcanvas-body">
		    <a class="nav-link" href="{% url 'student:dashboard' %}">
			<div class="sb-nav-link-icon">
				<!--<i class="fas fa-tachometer-alt"></i>-->
				<h3>Dashboard</h3>
			</div>
		    </a>
		    <a class="nav-link" href="{% url 'result:buy-card' %}">
			<div class="sb-nav-link-icon">
				<!-- <i class="fas fa-tachometer-alt"></i> -->
			</div>
			<h3>Get a Pin</h3>
		    </a>
		</div>
	</div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
			<h1 class="mt-4">{{ user.first_name }}</h1>
			<ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
			<div class='row'>
			    <div class="card-body">
			    {% block content %}
			    {% endblock content %}
			    </div>
			</div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; ResultHub 2024</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
	<script src="{% static 'js/scripts.js' %}"></script>
	<script src="{% static 'js/pay.js' %}"></script>
	<script src="{% static 'css/student/profile.css' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
	<script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
	<script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
	<script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
</html>

generics/templates/generics/student/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Login - SB Admin</title>
	<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
					<form method='post' action="{% url 'student:login' %}">
					    {% csrf_token %}
					    {% for fm in form %}
					    <div class="form-floating mb-3">
					        <div class="row mb-3">
                                                {{ fm }}
						<label for="{{ fm.id_for_label }}">{{ fm.label }}</label>
						<small class="text-danger">{{fm.errors|striptags}}</small>
					        </div>
					    </div>
					    {% endfor %}
                                            <div class="form-check mb-3">
                                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
					    </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="password.html">Forgot Password?</a>
                                                <button class="btn btn-primary">Login</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
					    <div class="small"><a href="{% url 'student:registration' %}">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

generics/templates/generics/student/student_profile.html
{% extends 'generics/student/index.html' %}
{% block title %} profile {% endblock title%}
{% block content %}
<div class='alert' mt-4>
    {% if messages %}
    {% for msg in messages %}
	<div class="alert alert-{{msg.tags}}" role="alert">
	{{msg}}
	</div>
    {% endfor %}
    {% endif %}
</div>
<!-- <img src="{{ student.profile_picture.url }}" class="img-thumbnail" width='200' height='100px' alt="..."> -->
<div class="card">
	<img src="{{ student.profile_picture.url }}" class="img-thumbnail ml-5 align-self-end mt-5 " height='25%'  width='30%' alt="...">
	<div class="card-body">
	  <!-- <h5 class="card-title">{{ user.username }}</h5> -->
	  {% if student.first_name %}
	  <hr>
	  <p> STUDENT NAME: {{ student.first_name }} {{ student.last_name }}</p>
	  <hr>
	  <p> MATRIC NUMBER: {{ student.matric_number }} </p>
	  <hr>
	  <p> ADDRESS: {{ student.state }} - ({{ student.city }}) </p>
	  <hr>
          <p> ZIPCODE: {{ student.zipcode }} </p>
	  <hr>
	  {% else %}
	  <p> update your profile </p>
	  {% endif %}
    <a href={% url "student:update" user.id %} class="btn btn-primary">Update Account</a>
    <a href={% url "student:delete" user.id %} class="btn btn-danger">Delete Account</a>
  </div>
</div>
{% endblock content %}

generics/templates/generics/student/student_update.html
{% extends 'generics/student/index.html' %}
{% load static %}
{% block title %}Profile{% endblock title%}
{% block content %}
<h3>Welcome <span class="text-capitalize">{{ student.first_name }}</span></h3>
    
        <div class="col-sm-2 border-end">
	    {% for st in form %}
	        {{ st.first_name }}
	    {% endfor %}
            <ul class="list-unstyled">
                <li class="d-grid"><a href="#" class="btn btn-primary">Profile</a></li>
            </ul>
	</div>
	<form class="row g-3" action="{% url 'student:update' user.id %}" method="post" enctype="multipart/form-data">
	<div class="justify-content-center">
	    <div class="col-md-6">
                {% csrf_token %}
                <!-- manually dispaly the form field with the help of for loop -->
                {% for fm in form %}
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br>
                {% endfor %}
                <div class="col-12 mt-3">
			<button type="submit" class="btn btn-primary">Update</button>
                </div>
                {% if form.non_field_error %}
                    {% for error in form.non_field_error %}
                    <p class="alert.alert-danger.my-3">{{error}}</p>
                    {%endfor%}
                {%endif%}

                {% if messages %}
                    {% for msg in messages %}
                    <div class="alert alert-{{msg.tags}}" role="alert">
                        {{msg}}
                    </div>
                    {% endfor %}
                {% endif %}
	</div>
        </form>
{% endblock content %}

generics/templates/generics/student/update.html
<h1>Update student</h1>

<form action="update/{{ student.id }}" method="post">
{% csrf_token %}
First Name:<br>
<input name="first" value="{{ student.firstname }}">
<br><br>
Last Name:<br>
<input name="last" value="{{ student.lastname }}">
<br><br>
<input type="submit" value="Submit">
</form>